-- AlterTable
ALTER TABLE "Chatbot" ADD COLUMN "color" TEXT DEFAULT '#3b82f6';
ALTER TABLE "Chatbot" ADD COLUMN "windowHeight" INTEGER DEFAULT 600;
ALTER TABLE "Chatbot" ADD COLUMN "windowWidth" INTEGER DEFAULT 380;
